blog/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings
from .views import CreatePostView
app_name='blog'
urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('post/<int:pk>',views.PostDetailView.as_view(),name='post_detail'),
    path('post/new/',views.CreatePostView.as_view(),name='post_new'),
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(),name='post_edit'),
    path('post/<int:pk>/remove/',views.PostDeleteView.as_view(),name='post_remove'),
    path('drafts/',views.DraftListView.as_view(),name='post_draft_list'),
    path('post/<int:pk>/comment/',views.add_comment_to_post,name='add_comment_to_post'),
    path('comment/<int:pk>/approve',views.comment_approve,name='comment_approve'),
    path('comment/<int:pk>/remove/',views.comment_remove,name='comment_remove'),
    path('post/<int:pk>/publish/',views.post_publish,name='post_publish'),
    path('like/<int:pk>',views.LikeView,name='like_post')
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

my_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.contrib.auth.views import LoginView, logout_then_login, LogoutView
# from django.conf.urls import url

from django.conf import settings

from django.views.static import serve

urlpatterns = [
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin_mirmushaid/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),
    path('todo_app/',include('todo_app.urls',namespace='todo_app')),
    path('',include("contents.urls",namespace='contents')),
    path('',include('accounts.urls',namespace='accounts')),
    path('',include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),


]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

todo_app/urls.py
from django.urls import path
from . import views
app_name='todo_app'

urlpatterns = [
    path("", views.ListListView.as_view(), name="index"),
    path("list/<int:list_id>/",views.ItemListView.as_view(), name="list"),
    path("list/add/", views.ListCreate.as_view(), name="list-add"),
    path("list/<int:list_id>/item/add/",views.ItemCreate.as_view(),name="item-add"),
    path("list/<int:list_id>/item/<int:pk>/",views.ItemUpdate.as_view(),name="item-update"),
    path(
        "list/<int:pk>/delete/", views.ListDelete.as_view(), name="list-delete"
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/delete/",
        views.ItemDelete.as_view(),
        name="item-delete",
    ),
]

todo_app/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
from django.urls import reverse
from django.contrib.auth import get_user_model
User=get_user_model()

def one_week_hence():
    return timezone.now() + timezone.timedelta(days=7)

class ToDoList(models.Model):
    title =models.CharField(max_length = 150,unique=True)
    def get_absolute_url(self):
        return reverse("todo_app:list", args=[self.id])

    def __str__(self):
        return self.title
   

class ToDoItem(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(default=one_week_hence)
    todo_list = models.ForeignKey(ToDoList, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse(
            "todo_app:item-update", args=[str(self.todo_list.id), str(self.id)]
        )

    def __str__(self):
        return f"{self.title}: due {self.due_date}"

    class Meta:
        ordering = ["due_date"]

todo_app/views.py
from django.urls import reverse,reverse_lazy

# Create your views here.
from django.views.generic import ListView,UpdateView,CreateView,DeleteView
from .models import ToDoList,ToDoItem


class ListListView(ListView):
    model = ToDoList
    template_name = "todo_app/index.html"

class ItemListView(ListView):
    model = ToDoItem
    template_name = "todo_app/todo_list.html"

    def get_queryset(self):
        return ToDoItem.objects.filter(todo_list_id=self.kwargs["list_id"])

    def get_context_data(self):
        context = super().get_context_data()
        context["todo_list"] = ToDoList.objects.get(id=self.kwargs["list_id"])
        return context

class ListCreate(CreateView):
    model = ToDoList
    fields = ["title"]

    def get_context_data(self):
        context = super(ListCreate, self).get_context_data()
        context["title"] = "Add a new list"
        return context

class ItemCreate(CreateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    def get_initial(self):
        initial_data = super(ItemCreate, self).get_initial()
        todo_list = ToDoList.objects.get(id=self.kwargs["list_id"])
        initial_data["todo_list"] = todo_list
        return initial_data

    def get_context_data(self):
        context = super(ItemCreate, self).get_context_data()
        todo_list = ToDoList.objects.get(id=self.kwargs["list_id"])
        context["todo_list"] = todo_list
        context["title"] = "Create a new item"
        return context

    def get_success_url(self):
        return reverse("todo_app:list", args=[self.object.todo_list_id])

class ItemUpdate(UpdateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    def get_context_data(self):
        context = super(ItemUpdate, self).get_context_data()
        context["todo_list"] = self.object.todo_list
        context["title"] = "Edit item"
        return context

    def get_success_url(self):
        return reverse("todo_app:list", args=[self.object.todo_list_id])
class ListDelete(DeleteView):
    model = ToDoList
    # You have to use reverse_lazy() instead of reverse(),
    # as the urls are not loaded when the file is imported.
    success_url = reverse_lazy("todo_app:index")

class ItemDelete(DeleteView):
    model = ToDoItem

    def get_success_url(self):
        return reverse_lazy("todo_app:list", args=[self.kwargs["list_id"]])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["todo_list"] = self.object.todo_list
        return context

templates/todo_app/index.html
{% extends "./sub_base.html" %}
{% block content %}
<!--index.html-->
{% if object_list %}
<h3>All my lists</h3>
{% endif %}
<ul>
    {% for todolist in object_list %}
    <li>
        <div
            role="button"
            onclick="location.href='{% url "todo_app:list" todolist.id %}'">
            {{ todolist.title }}
        </div>
    </li>
    {% empty %}
    <h4>You have no lists!</h4>

    {% endfor %}
</ul>
<div>
    <button><a href="{% url 'todo_app:list-add' %}">Add List</a></button>
</div>


{% endblock %}

templates/todo_app/sub_base.html
{% extends '../base.html' %}
    <div>
        <h1 onclick="location.href='{% url "todo_app:index" %}'">
            Django To-do Lists
        </h1>
    </div>
    <div>
        {% block content %}
        This content will be replaced by different html code for each page.
        {% endblock %}
    </div>
<

templates/todo_app/todo_list.html
<!-- todo_list/todo_app/templates/todo_app/todo_list.html -->
{% extends "./sub_base.html" %}

{% block content %}
<div>
    <div>
        <div>
            <h3>Edit list:</h3>
            <h5>{{ todo_list.title | upper }}</h5>
        </div>
        <ul>
            {% for todo in object_list %}
            
            <li>
                <div>
                    <div
                        role="button"
                        onclick="location.href=
                        '{% url "todo_app:item-update" todo_list.id todo.id %}'">
                        {{ todo.title }}
                        (Due {{ todo.due_date | date:"l, F j"}})
                    </div>
                </div>
            </li>
            {% empty %}
            <p>There are no to-do items in this list.</p>
            {% endfor %}
        </ul>
        <p>
            <input
                value="Add a new item"
                type="button"
                onclick="location.href='{% url "todo_app:item-add" todo_list.id %}'"/>
                <input
                value="Delete this list"
                type="button"
                onclick="location.href=
                '{% url "todo_app:list-delete" todo_list.id %}'" />
        </p>
    </div>
</div>
{% endblock %}

templates/todo_app/todoitem_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h3>Delete To-do Item</h3>

<p>Are you sure you want to delete the item: <b>{{ object.title }}</b>
   from the list <i>{{ todo_list.title }}</i>?</p>

<form method="POST">
    {% csrf_token %}
    <input
        value="Yes, delete."
        type="submit">
    <input
        value="Cancel"
        type="button"
        onclick="location.href='{% url "todo_app:list" todo_list.id %}'">
</form>

{% endblock %}

templates/todo_app/todoitem_form.html
{% extends "base.html" %}

{% block content %}

<h3>{{ title }}</h3>
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input
        value="Submit"
        type="submit">
    <input
        value="Cancel"
        type="button"
        onclick="location.href='{% url "todo_app:list" todo_list.id %}'">

        {% if object %}
        <input
            value="Delete this item"
            type="button"
            onclick="location.href=
            '{% url "todo_app:item-delete" todo_list.id object.id %}'">
    {% endif %}
</form>

{% endblock %}

templates/todo_app/todolist_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<!--todolist_confirm_delete.html-->

<h3>Delete List</h3>

<p>Are you sure you want to delete the list <i>{{ object.title }}</i>?</p>

<form method="POST">
    {% csrf_token %}
    <input
        value="Yes, delete."
        type="submit">
</form>
<input
    value="Cancel"
    type="button"
    onclick="location.href='{% url "todo_app:index" %}';">

{% endblock %}

templates/todo_app/todolist_form.html
{% extends "base.html" %}

{% block content %}

<h3>{{ title }}</h3>
<div>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input
                value="Save"
                type="submit">
            <input
                value="Cancel"
                type="button"
                onclick="location.href='{% url "todo_app:index" %}'">
        </form>
    </div>
</div>

{% endblock %}