blog/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings
from .views import CreatePostView
app_name='blog'
urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('post/<int:pk>',views.PostDetailView.as_view(),name='post_detail'),
    path('post/new/',views.CreatePostView.as_view(),name='post_new'),
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(),name='post_edit'),
    path('post/<int:pk>/remove/',views.PostDeleteView.as_view(),name='post_remove'),
    path('drafts/',views.DraftListView.as_view(),name='post_draft_list'),
    path('post/<int:pk>/comment/',views.add_comment_to_post,name='add_comment_to_post'),
    path('comment/<int:pk>/approve',views.comment_approve,name='comment_approve'),
    path('comment/<int:pk>/remove/',views.comment_remove,name='comment_remove'),
    path('post/<int:pk>/publish/',views.post_publish,name='post_publish'),
    path('like/<int:pk>',views.LikeView,name='like_post')
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

my_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.contrib.auth.views import LoginView, logout_then_login, LogoutView
# from django.conf.urls import url

from django.conf import settings

from django.views.static import serve

urlpatterns = [
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin_mirmushaid/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),
    path('todo_app/',include('todo_app.urls',namespace='todo_app')),
    path('',include("contents.urls",namespace='contents')),
    path('',include('accounts.urls',namespace='accounts')),
    path('',include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),


]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import  reverse
from django.contrib.auth import get_user_model
from sqlalchemy import null, true
from PIL import Image
from tinymce.models import HTMLField
User=get_user_model()


# Create your models here.
class Post(models.Model):
    # author=models.ForeignKey(User,on_delete=models.CASCADE,default=True)
    title=models.CharField(max_length=200)
    short_desc=models.TextField(default=True)
    text = HTMLField()
    image=models.ImageField(upload_to='profile_pics',null=True)
    created_date=models.DateTimeField(default=timezone.now())
    published_date=models.DateTimeField(blank=True,null=True)
    likes=models.ManyToManyField(User,related_name='blog_posts')
    home=models.BooleanField(help_text="select this blog for home page",default=False)
    def total_likes(self):
        return self.likes.count()
        
    def home1(self):
        self.home=True
        self.save()
    def owner1(self):
        self.owner=True
        self.save()
    def publish(self):
        self.published_date=timezone.now()
        self.save()
    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.pk})
    
    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        # run the parent class' save() function:
        super().save(*args, **kwargs)

        # open the image of the current instance:
        image = Image.open(self.image.path)

        if image.height > 425 or image.width > 425:
            output_size = (425, 425)
            image.thumbnail(output_size)
        image.save(self.image.path)

class Comment(models.Model):
    post=models.ForeignKey('blog.Post',on_delete=models.CASCADE,related_name='comments')
    # author=models.ForeignKey(UserWarning,on_delete=models.CASCADE,default=True)
    text=models.TextField()
    create_date=models.DateTimeField(default=timezone.now())
    approved_comment=models.BooleanField(default=False)

    def approve(self):
        self.approved_comment=True
        self.save()
    def get_absolute_url(self):
        return reverse('post_list')
    def __str__(self):
        return self.text

blog/forms.py
from dataclasses import fields
from django import forms
from blog.models import Post,Comment

class PostForm(forms.ModelForm):
    class Meta():
        model=Post
        fields=('title','short_desc','text','image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
            'short_desc': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),

        }
class CommentForm(forms.ModelForm):
    class Meta():
        model=Comment
        fields=('text',)
        widgets = {
            # 'author': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }

blog/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from pytz import timezone
from blog.forms import PostForm,CommentForm
from django.utils import timezone
from blog.models import Post,Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import  datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def LikeView(request,pk):
    post=get_object_or_404(Post,pk=pk)
    liked=False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked=False
    else:
        post.likes.add(request.user)
        liked=True
    return HttpResponseRedirect(reverse('blog:post_detail',args=[str(pk)] ))
    
    



class AboutView(TemplateView):
    template_name='blog/about.html'


class PostListView(ListView):
    model=Post
    

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')

class PostDetailView(DetailView):
    model=Post
    def get_context_data(self, *args,**kwargs):
        context=super(PostDetailView,self).get_context_data(**kwargs)
        stuff=get_object_or_404(Post,id=self.kwargs['pk'])
        total_likes=stuff.total_likes()

        liked=False
        if stuff.likes.filter(id=self.request.user.id).exists():
            liked=True
        context["total_likes"]=total_likes
        context["liked"]=liked
        return context


class CreatePostView(LoginRequiredMixin,CreateView):
    login_url='/login/'
    redirect_field_name='blog/post_detail.html'
    form_class=PostForm
    model=Post
# @login_required
# def CreatePostView(request,pk):
#     post=get_object_or_404(Post,pk=pk)
#     if request.method=="POST":
#         form=PostForm(request.POST,request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('blog:post_detail',pk=post.pk)
#     else:
#             form=PostForm()
#     return render(request,'blog/post_form.html',{'form':form})


class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url='/login/'
    redirect_field_name='blog/post_detail.html'
    form_class=PostForm
    model=Post

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model=Post
    success_url=reverse_lazy('blog:post_list')

class DraftListView(LoginRequiredMixin,ListView):
    login_url='/login/'
    redirect_field_name='blog/post_list.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')


##########################################################
##########################################################


@login_required
def post_publish(request,pk):
    post=get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('blog:post_detail',pk=pk)


@login_required
def add_comment_to_post(request,pk):
    post=get_object_or_404(Post,pk=pk)
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.save()
            return redirect('blog:post_detail',pk=post.pk)
    else:
        form=CommentForm()
    return render(request,'blog/comment_form.html',{'form':form})


@login_required
def comment_approve(request,pk):
    comment=get_object_or_404(Comment,pk=pk)
    comment.approve()
    return redirect('blog:post_detail',pk=comment.post.pk)

@login_required
def comment_remove(request,pk):
    comment=get_object_or_404(Comment,pk=pk)
    post_pk=comment.post.pk
    comment.delete()
    return redirect('blog:post_detail',pk=post_pk)

templates/blog/comment_form.html
{% extends 'base.html' %}
{% block content %}
<h1>new comment</h1>
<form class='post-form' method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button class="save btn btn-default" type="submit">Post Comment</button>
</form>
<script>
    var editor = new MediumEditor('.editable');
</script>



{% comment %} <style>
    .footer {
       position: silver;
       left: 0;
       bottom: 0;
       width: 100%;
       background-color: white;
       color: white;
       text-align: center;
    }
    </style>
<div class="footer">
    <p>
        &copy
        <script>
           document.write(new Date().getFullYear());
        </script> 
        <a style="background-color:white ;" href="">Mir Mushaid</a>
        <script>
          fetch('http://worldclockapi.com/api/json/utc/now')
          .then(data => data.json())
          .then(d => 
          document.getElementById('copyright').innerHTML = (new Date(d.currentDateTime).getFullYear())
        )
        </script>
        <!-- <a href='https://twiter.com/saviour123>Saviour Gidi<a/> -->
        </p>
  </div> {% endcomment %}
  

{% endblock content %}

templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>are you sure you want to delete {{object}}</p>
    <input class="btn btn-danger" type="submit" value="confirm">
</form>
  

{% comment %} 
<style>
    .footer {
       position: fixed;
       left: 0;
       bottom: 0;
       width: 100%;
       background-color: silver;
       color: white;
       text-align: center;
    }
    </style>
<div class="footer">
    <p>
        &copy
        <script>
           document.write(new Date().getFullYear());
        </script> 
        <a style="background-color:white ;" href="">Mir Mushaid</a>
        <script>
          fetch('http://worldclockapi.com/api/json/utc/now')
          .then(data => data.json())
          .then(d => 
          document.getElementById('copyright').innerHTML = (new Date(d.currentDateTime).getFullYear())
        )
        </script>
        <!-- <a href='https://twiter.com/saviour123>Saviour Gidi<a/> -->
        </p>
  </div>
   {% endcomment %}

{% endblock content %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<h1 class="posttitle loader">{{ post.title }}</h1>


    
{% comment %} <h1>{{post.author}}</h1> {% endcomment %}

{% if post.published_date %}
<div class="date postdate">
    {{post.published_date}}
</div>
{% else %}
<a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
    
{% endif %}
{% comment %} <p class="postcontent">{{ post.title|safe|linebreaksbr}}</p> {% endcomment %}
<p class="postcontent">{{ post.text|safe|linebreaksbr}}</p>


{% if user.is_authenticated %}
{% if user.is_superuser %}    
<a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}">
<span class="glyphicon glyphicon-pencil"></span>
</a>

<a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}">
    <span class="glyphicon glyphicon-remove"></span>
</a>
{% endif %}
{% endif %}

    <hr>
    <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>
    


    <div class="container">
        
        {% for comment in post.comments.all %}
        <br>
        
        {% if user.is_authenticated or comment.approved_comment %}
        {{ comment.created_date }}
        
        {% if not comment.approved_comment %}
        <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}">
            <span class="glyphicon glyphicon-remove"></span>
        </a>
        <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}">
            <span class="glyphicon glyphicon-ok"></span>
        </a>
            
        {% endif %}
            <p>{{comment.text|safe|linebreaks}}</p>
            {% comment %} <p>Posted By : {{comment.author}}</p> {% endcomment %}
            
        {% endif %}
            {% empty %}
            <p>No Comments!</p>
            
        {% endfor %}
            
    </div>

    <div>
<form action="{% url 'blog:like_post' post.pk %}" method="POST">
    {% csrf_token %}

    {% if user.is_authenticated %}
    {% if liked %}
    <button type='submit',name='post_id',value='{{post.id}}',class='btn btn-danger btn-sm'>unlike</button>
    
        {% else %}
    <button type='submit',name='post_id',value='{{post.id}}',class='btn btn-primary btn-sm'>like</button>
    {% endif %}
    {% else %}

    {% endif %}
    - {{total_likes}} likes
</form>
    </div>
    


    {% comment %} <style>
        .footer {
           position: fixed;
           left: 0;
           bottom: 0;
           width: 100%;
           background-color: silver;
           color: white;
           text-align: center;
        }
        </style>
    <div class="footer">
        <p>
            &copy
            <script>
               document.write(new Date().getFullYear());
            </script> 
            <a style="background-color:white ;" href="">Mir Mushaid</a>
            <script>
              fetch('http://worldclockapi.com/api/json/utc/now')
              .then(data => data.json())
              .then(d => 
              document.getElementById('copyright').innerHTML = (new Date(d.currentDateTime).getFullYear())
            )
            </script>
            <!-- <a href='https://twiter.com/saviour123>Saviour Gidi<a/> -->
            </p>
      </div> {% endcomment %}

{% endblock content %}

templates/blog/post_draft_list.html
{% extends 'base.html' %}
{% block content %}

{% for post in posts %}
<div class='post'>
    <p class='date'> Created: {{post.created_date|date:'d-m-Y'}}</p>
    <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a> </h1>
    <p>{{post.text|truncatechars:200}}</p>
</div>

{% endfor %}


<style>
    .footer {
       position: fixed;
       left: 0;
       bottom: 0;
       width: 100%;
       background-color: silver;
       color: white;
       text-align: center;
    }
    </style>
<div class="footer">
    <p>
        &copy
        <script>
           document.write(new Date().getFullYear());
        </script> 
        <a style="background-color:white ;" href="">Mir Mushaid</a>
        <script>
          fetch('http://worldclockapi.com/api/json/utc/now')
          .then(data => data.json())
          .then(d => 
          document.getElementById('copyright').innerHTML = (new Date(d.currentDateTime).getFullYear())
        )
        </script>
        <!-- <a href='https://twiter.com/saviour123>Saviour Gidi<a/> -->
        </p>
  </div>

{% endblock content %}

templates/blog/post_form.html
{% extends 'base.html' %}
{% block content %}
<h1>New Post</h1>
<form class="post-form"  method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<button type="submit" class="save btn btn-default">save</button>
</form>
<script>
    var editor = new MediumEditor('.editable');
</script>



<style>
    .footer {
       position: fixed;
       left: 0;
       bottom: 0;
       width: 100%;
       background-color: silver;
       color: white;
       text-align: center;
    }
    </style>
{% comment %} <div class="footer">
    <p>
        &copy
        <script>
           document.write(new Date().getFullYear());
        </script> 
        <a style="background-color:white ;" href="">Mir Mushaid</a>
        <script>
          fetch('http://worldclockapi.com/api/json/utc/now')
          .then(data => data.json())
          .then(d => 
          document.getElementById('copyright').innerHTML = (new Date(d.currentDateTime).getFullYear())
        )
        </script>
        <!-- <a href='https://twiter.com/saviour123>Saviour Gidi<a/> -->
        </p>
  </div> {% endcomment %}


{% endblock content %}

templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="{% static 'footer1.css' %}">


<div class="destinations" id="destinations">
    <div class="container">
    <div class="row">
    <div  class="col text-center">
    <div  class="section_subtitle">
    Simply Amazing 
    </div>
    <div class="section_title">
        <h2>Popular Blogs</h2>
    </div>
    
    </div>
    </div>
    <div  class="row destinations_row">
    <div class="col">
    <div class="destinations_container item_grid">
        {% for post in post_list %}
        
        {% if post.home %}
          
        
          
        <div class="destination item">
            <div class="destination_title">
                <a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a>
            </div>
    <div class="destination_image">
        <img src="{{post.image.url}}" alt="" ALIGN="left">
        <!-- <div class="text"> -->
         
          <p>{{post.short_desc|safe|linebreaksbr}}</p>
        <!-- </div> -->

    </div>
    <div class="destination_content">
    <div class="card-footer">
    <div class="row">
    <div class="col">
        <a href="{% url 'blog:post_detail' pk=post.pk %}" class="btn btn-primary">More</a>
        <a href="{% url 'blog:post_detail' pk=post.pk %}" class="btn btn-primary"><i id="mark1" class="glyphicon glyphicon-bookmark" ></i></a>
    
    </div>
    <div class="col">
    <div class="text-right">
        <button type="button" class="btn btn-outline-secondary">

            <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
           
          </button>
    
          <button type="button" class="btn btn-outline-danger">

                <a href="{% url 'blog:post_detail' pk=post.pk %}">Likes: {{post.likes.count}}</a>

          </button>
    </div>
    </div>
    </div>
    </div>
    </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    </div>
    </div>
    </div>
    </div>

   




{% endblock %}