accounts/urls.py
from importlib.resources import path
import re
from unicodedata import name
from django.contrib.auth import views as auth_views
#from django.conf.urls import url
from django.urls import re_path
from .import views
from django.contrib.auth.views import LoginView, logout_then_login, LogoutView
from django.conf.urls.static import static
from django.conf import settings
app_name='accounts'

urlpatterns = [
    re_path('login/',auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    re_path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    re_path('signup/',views.SignUp.as_view(),name='signup')    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings
from .views import CreatePostView
app_name='blog'
urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('post/<int:pk>',views.PostDetailView.as_view(),name='post_detail'),
    path('post/new/',views.CreatePostView.as_view(),name='post_new'),
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(),name='post_edit'),
    path('post/<int:pk>/remove/',views.PostDeleteView.as_view(),name='post_remove'),
    path('drafts/',views.DraftListView.as_view(),name='post_draft_list'),
    path('post/<int:pk>/comment/',views.add_comment_to_post,name='add_comment_to_post'),
    path('comment/<int:pk>/approve',views.comment_approve,name='comment_approve'),
    path('comment/<int:pk>/remove/',views.comment_remove,name='comment_remove'),
    path('post/<int:pk>/publish/',views.post_publish,name='post_publish'),
    path('like/<int:pk>',views.LikeView,name='like_post')
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.views.generic import TemplateView
from .views import *

app_name = 'core'

urlpatterns = [
        path('', views.index, name='home'),
        path('search/', views.search, name='search'),
        path('<slug:slug>/', category, name='main-category-detail'),
        path('news/<slug>/', views.news_details, name='news-detail'),
        path('tag/<slug:slug>/', views.tagged, name='tag-detail'),
        path('page/<slug:slug>/', PageDetailView.as_view(), name='page-detail'),


        # path('news/<slug:slug>/', NewsDetailView.as_view(), name='news-detail'),


]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.contrib.auth.views import LoginView, logout_then_login, LogoutView
# from django.conf.urls import url

from django.conf import settings

from django.views.static import serve

urlpatterns = [
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin_mirmushaid/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),
    path('todo_app/',include('todo_app.urls',namespace='todo_app')),
    path('',include("contents.urls",namespace='contents')),
    path('',include('accounts.urls',namespace='accounts')),
    path('',include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),


]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

todo_app/urls.py
from django.urls import path
from . import views
app_name='todo_app'

urlpatterns = [
    path("", views.ListListView.as_view(), name="index"),
    path("list/<int:list_id>/",views.ItemListView.as_view(), name="list"),
    path("list/add/", views.ListCreate.as_view(), name="list-add"),
    path("list/<int:list_id>/item/add/",views.ItemCreate.as_view(),name="item-add"),
    path("list/<int:list_id>/item/<int:pk>/",views.ItemUpdate.as_view(),name="item-update"),
    path(
        "list/<int:pk>/delete/", views.ListDelete.as_view(), name="list-delete"
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/delete/",
        views.ItemDelete.as_view(),
        name="item-delete",
    ),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
      
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
        <title>Blog Project</title>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>







        <!-- Latest compiled and minified CSS -->
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- Optional theme -->
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        {# MEDIUM STYLE EDITOR#}
        <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
        {# Custom CSS#}
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link rel="stylesheet" href="{% static 'ft.css' %}">
        <link rel="stylesheet" href="{% static 'footer1.css' %}">


        {# Fonts#}
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />

        <style>

          body {
            font-family: "Lato", sans-serif;
          }
          
          .sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
          }
          
          .sidebar a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            transition: 0.3s;
          }
          
          .sidebar a:hover {
            color: #f1f1f1;
          }
          
          .sidebar .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
          }
          
          .openbtn {
            font-size: 20px;
            cursor: pointer;
            background-color:black;
            color: white;
            padding: 5px 10px;
            border: none;
          }
          
          .openbtn:hover {
            background-color: #444;
          }
          
          #main {
            transition: margin-left .5s;
            padding: 5px;
            
          }
          
          /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
          @media screen and (max-height: 450px) {
            .sidebar {padding-top: 15px;}
            .sidebar a {font-size: 18px;}
          }


          </style>

    </head>

<body class='loader'>

  <nav class="navbar navbar-default techfont custom-navbar">
    <div class="container">

      <div id="mySidebar" class="sidebar">
        

        <ul>
        <li><a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a></li>
        <li><a href="{% url 'contents:home' %}"><span class="glyphicon glyphicon-user"></span></a></li>
        <li><a href="" target="blank"><i class="fa fa-instagram"></i></a></li>
        <a href=""><i class="fa fa-linkedin"></i></a>
        <a href="" target="_blank"><i class="fa fa-github"></i></a>
        

        </ul>

      </div>

      <script>
        function openNav() {
          document.getElementById("mySidebar").style.width = "250px";
          document.getElementById("main").style.marginLeft = "250px";
        }
        
        function closeNav() {
          document.getElementById("mySidebar").style.width = "0";
          document.getElementById("main").style.marginLeft= "0";
        }
        </script>

      <ul class="nav navbar-nav">

        <li id="main"><button class="openbtn" onclick="openNav()">☰</button></li>
        <li><a class='navbar-brand bigbrand' href="{% url 'blog:post_list' %}">Kash Blog</a></li>
        <li><a class='navbar-brand bigbrand' href="{% url 'contents:home' %}">Home</a></li>
        

      </ul>

      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'blog:post_new' %}" >New Post</a>
        </li>

        <li>
          <a href="{% url 'blog:post_draft_list' %}">Drafts</a>
        </li>
        <li>
          <a href="{% url 'accounts:logout' %}" >Log out</a>
        </li>
        
        <li>
          <a href="{% url 'todo_app:index' %}">My Todos</a>
        </li>

        <li>
          <a >Welcome: {{ user.username }} {{user.image}}</a>
        </li>
          {% else %}
          <li><a href="{% url 'accounts:signup' %}">signup</a></li>
          <li><a class='nav navbar-right' href="{% url 'accounts:login' %}" ><span class="glyphicon glyphicon-user"></span></a></li>
        {% endif %}

      </ul>
  </div>
</nav>





<div class="container-fluid">
  
</div>
  {# The actual blog posts#}
  </div>
        <div class="content container">
            <div class="row">
                <div class="col-lg-6">
                  <div class="blog_posts">

                    {% block content %}

                    {% endblock %}
                  </div>
                </div>

              </div>
        </div> 

{# SCRIPTS#}
<script src="//code.jivosite.com/widget/F4aLsjrQrN" async></script>								

<script type="text/javascript" src="{% static 'js/blog.js' %}"></script> 


<div class="container">
  <section style="height:80px;"></section>
<div class="row" style="text-align:center;">
  <!-- <h2>Bootstrap Dark Footer UI</h2> -->
</div>
  <!----------- Footer ------------>
  <footer class="footer-bs">
      <div class="row">
        <div class="col-md-3 footer-brand animated fadeInLeft">
            <h2>{{seej.profile.title}}</h2>
              <p>Suspendisse hendrerit tellus laoreet luctus pharetra. Aliquam porttitor vitae orci nec ultricies. Curabitur vehicula, libero eget faucibus faucibus, purus erat eleifend enim, porta pellentesque ex mi ut sem.</p>
              <p></p>
          </div>
        <div class="col-md-4 footer-nav animated fadeInUp">
            <h4>Menu —</h4>
            <div class="col-md-6">
                  <ul class="pages">
                      <li><a href="#">Travel</a></li>
                      <li><a href="#">Nature</a></li>
                      <li><a href="#">Explores</a></li>
                      <li><a href="#">Science</a></li>
                      <li><a href="#">Advice</a></li>
                  </ul>
              </div>
            <div class="col-md-6">
                  <ul class="list">
                      <li><a href="#">About Us</a></li>
                      <li><a href="#">Contacts</a></li>
                      <li><a href="#">Terms & Condition</a></li>
                      <li><a href="#">Privacy Policy</a></li>
                  </ul>
              </div>
          </div>
        <div class="col-md-2 footer-social animated fadeInDown">
            <h4>Follow Us</h4>
            <ul>
              <li><a href="{{seej.profile.instagram_url}}"><i class="fa fa-instagram"></i>Instagram</a></li>
              <li><a href="{{seej.profile.linkedin_url}}"><i class="fa fa-linkedin"></i>Linkedin</a></li>
              <li><a href="{{seej.profile.github_url}}"><i class="fa fa-github"></i>Github</a></li>
              </ul>
          </div>
        <div class="col-md-3 footer-ns animated fadeInRight">
            <h4>Newsletter</h4>
              <p>A rover wearing a fuzzy suit doesn’t alarm the real penguins</p>
              <p>
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-envelope"></span></button>
                    </span>
                  </div><!-- /input-group -->
               </p>
          </div>
      </div>
  </footer>
  <section style="text-align:center; margin:10px auto;"><p>
    &copy
    <script>
       document.write(new Date().getFullYear());
    </script> 
    <a style="background-color:white ;" href="">Mir Mushaid</a>
    <script>
      fetch('http://worldclockapi.com/api/json/utc/now')
      .then(data => data.json())
      .then(d => 
      document.getElementById('copyright').innerHTML = (new Date(d.currentDateTime).getFullYear())
    )
    </script>
    <!-- <a href='https://twiter.com/saviour123>Saviour Gidi<a/> -->
    </p></section>

</div>


</body>

</html>

templates/base1.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <style>


.sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
          }
          
          .sidebar a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            transition: 0.3s;
          }
          
          .sidebar a:hover {
            color: #f1f1f1;
          }
          
          .sidebar .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
          }
          
          .openbtn {
            font-size: 20px;
            cursor: pointer;
            background-color:black;
            color: white;
            padding: 5px 10px;
            border: none;
          }
          
          .openbtn:hover {
            background-color: #444;
          }
          
          #main {
            transition: margin-left 0.5s;
            padding: 5px;
            
          }
          
          /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
          @media screen and (max-height: 450px) {
            .sidebar {padding-top: 15px;}
            .sidebar a {font-size: 18px;}
          }

    </style>
    <meta charset="UTF-8">
    <title>Mir Mushaid Web Portfolio</title>
    <!-- Required meta tags -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Mir Mushaid's web portfolio" />
    <meta name="keywords" content="Mushaid, resume, cv, portfolio" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" href="{% static 'assets/images/icon.png' %}">

    <!-- Google Font-->
    <link href="http://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'assets/icons/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets/plugins/css/bootstrap.min.css' %}">
    <!-- Animate CSS-->
    <link rel="stylesheet" href="{% static 'assets/plugins/css/animate.css' %}">
    <!-- Owl Carousel CSS-->
    <link rel="stylesheet" href="{% static 'assets/plugins/css/owl.css' %}">
    <!-- Fancybox-->
    <link rel="stylesheet" href="{% static 'assets/plugins/css/jquery.fancybox.min.css' %}">

    <!-- Custom CSS-->
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">

    <!-- Colors -->
    <link rel="stylesheet" href="{% static 'assets/css/colors/blue-munsell.css' %}" title="blue-munsell">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'footer1.css' %}">
    <style>
        h2, h3, h4, li, p {
            color: #100e17;
        }
    </style>
</head>
<body>
    <!-- Start Loader -->
    <div class="section-loader">
        <div class="loader">
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- End Loader -->

    <header class="black-bg mh-header mh-fixed-nav nav-scroll mh-xs-mobile-nav" id="mh-header" style="background-color: rgba(255, 255, 255, 0.8)">
{#        <div class="overlay"></div>#}
        <div class="container">
            <div class="row">
                <nav class="navbar navbar-expand-lg mh-nav nav-btn">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      <div id="mySidebar" class="sidebar">
        

                        <ul>
                        <li><a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a></li>
                        <a href="{% url 'contents:home' %}"><span class="glyphicon glyphicon-user"></span></a>
                        <a href="{{seej.profile.instagram_url}}" target="blank"><i class="fa fa-instagram"></i></a>
                        <a href="{{seej.profile.linkedin_url}}"><i class="fa fa-linkedin"></i></a>
                        <a href="{{seej.profile.github_url}}" target="_blank"><i class="fa fa-github"></i></a>
                        

                        
                
                        </ul>
                
                      </div>
                    <script>
                        function openNav() {
                          document.getElementById("mySidebar").style.width = "250px";
                          document.getElementById("main").style.marginLeft = "250px";
                        }
                        
                        function closeNav() {
                          document.getElementById("mySidebar").style.width = "0";
                          document.getElementById("main").style.marginLeft= "0";
                        }
                        </script>
                            <li id="main"><button class="openbtn" onclick="openNav()">☰</button></li>
                        <ul class="navbar-nav mr-auto ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="#mh-home">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#mh-about">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#mh-skills">Skills</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#mh-experience">Experiences</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#mh-portfolio">Projects</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#mh-certification">Certifications</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#mh-testimonial">Recommendations</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>    
    </header>


   


    {% block content %}
    {% endblock %}


      


    <div class="container">
      <section style="height:80px;"></section>
    <div class="row" style="text-align:center;">
      <!-- <h2>Bootstrap Dark Footer UI</h2> -->
    </div>
      <!----------- Footer ------------>
      <footer class="footer-bs">
          <div class="row">
            <div class="col-md-3 footer-brand animated fadeInLeft">
                <h2>{{ seej.profile.title }}</h2>
                  <p>Suspendisse hendrerit tellus laoreet luctus pharetra. Aliquam porttitor vitae orci nec ultricies. Curabitur vehicula, libero eget faucibus faucibus, purus erat eleifend enim, porta pellentesque ex mi ut sem.</p>
                  <p></p>
              </div>
            <div class="col-md-4 footer-nav animated fadeInUp">
                <h4>Menu —</h4>
                <div class="col-md-6">
                      <ul class="pages">
                          <li><a href="#">Travel</a></li>
                          <li><a href="#">Nature</a></li>
                          <li><a href="#">Explores</a></li>
                          <li><a href="#">Science</a></li>
                          <li><a href="#">Advice</a></li>
                      </ul>
                  </div>
                <div class="col-md-6">
                      <ul class="list">
                          <li><a href="#">About Us</a></li>
                          <li><a href="#">Contacts</a></li>
                          <li><a href="#">Terms & Condition</a></li>
                          <li><a href="#">Privacy Policy</a></li>
                      </ul>
                  </div>
              </div>
            <div class="col-md-2 footer-social animated fadeInDown">
                <h4>Follow Us</h4>
                <ul>
                    <li><a href="{{seej.profile.instagram_url}}"><i class="fa fa-instagram"></i>Instagram</a></li>
                    <li><a href="{{seej.profile.linkedin_url}}"><i class="fa fa-linkedin"></i>Linkedin</a></li>
                    <li><a href="{{seej.profile.github_url}}"><i class="fa fa-github"></i>Github</a></li>
                  </ul>
              </div>
            <div class="col-md-3 footer-ns animated fadeInRight">
                <h4>Newsletter</h4>
                  <p>A rover wearing a fuzzy suit doesn’t alarm the real penguins</p>
                  <p>
                      <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                          <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-envelope"></span></button>
                        </span>
                      </div><!-- /input-group -->
                   </p>
              </div>
          </div>
      </footer>
      <section style="text-align:center; margin:10px auto;"><p>
        &copy
        <script>
           document.write(new Date().getFullYear());
        </script> 
        <a style="background-color:white ;" href="">Mir Mushaid</a>
        <script>
          fetch('http://worldclockapi.com/api/json/utc/now')
          .then(data => data.json())
          .then(d => 
          document.getElementById('copyright').innerHTML = (new Date(d.currentDateTime).getFullYear())
        )
        </script>
        <!-- <a href='https://twiter.com/saviour123>Saviour Gidi<a/> -->
        </p></section>
  
  </div>
    <!-- Footer -->

    <!-- jQuery -->
    <script src="{% static 'assets/plugins/js/jquery.min.js' %}"></script>
    <!-- popper -->
    <script src="{% static 'assets/plugins/js/popper.min.js' %}"></script>
    <!-- bootstrap -->
    <script src="{% static 'assets/plugins/js/bootstrap.min.js' %}"></script>
    <!-- owl carousel -->
    <script src="{% static 'assets/plugins/js/owl.carousel.js' %}"></script>
    <!-- validator -->
    <script src="{% static 'assets/plugins/js/validator.min.js' %}"></script>
    <!-- wow -->
    <script src="{% static 'assets/plugins/js/wow.min.js' %}"></script>
    <!-- mixin js-->
    <script src="{% static 'assets/plugins/js/jquery.mixitup.min.js' %}"></script>
    <!-- circle progress-->
    <script src="{% static 'assets/plugins/js/circle-progress.js' %}"></script>
    <!-- jquery nav -->
    <script src="{% static 'assets/plugins/js/jquery.nav.js' %}"></script>
    <!-- Fancybox js-->
    <script src="{% static 'assets/plugins/js/jquery.fancybox.min.js' %}"></script>
    <!-- Map api -->
    <script src="http://maps.googleapis.com/maps/api/js?v=3.exp&amp;key=AIzaSyCRP2E3BhaVKYs7BvNytBNumU0MBmjhhxc"></script>
    <!-- isotope js-->
    <script src="{% static 'assets/plugins/js/isotope.pkgd.js' %}"></script>
    <script src="{% static 'assets/plugins/js/packery-mode.pkgd.js' %}"></script>
    <!-- Custom Scripts-->
    <script src="{% static 'assets/js/map-init.js' %}"></script>
    <script src="{% static 'assets/js/custom-scripts.js' %}"></script>
    <script src="//code.jivosite.com/widget/F4aLsjrQrN" async></script>								

</body>
</html>

{% comment %} <p>
  &copy
  <script>
     document.write(new Date().getFullYear());
  </script> 
  <a style="background-color:white ;" href="">Mir Mushaid</a>
  <script>
    fetch('http://worldclockapi.com/api/json/utc/now')
    .then(data => data.json())
    .then(d => 
    document.getElementById('copyright').innerHTML = (new Date(d.currentDateTime).getFullYear())
  )
  </script>
  <!-- <a href='https://twiter.com/saviour123>Saviour Gidi<a/> -->
  </p> {% endcomment %}